name: riverbloc
description: >-
  BlocProvider implementation with riverpod as alternative to provider
version: 1.0.0-dev.1
homepage: https://github.com/kranfix/riverbloc/tree/master/packages/riverbloc
repository: https://github.com/kranfix/riverbloc

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^1.0.0-dev.7
  bloc: ^7.2.0-dev.1
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.2
  mocktail: ^0.1.4
  #flutter_coverage_badge: ^0.0.1+1

flutter:
